"""upgrade

Revision ID: 1a8657b25530
Revises: c83c79c07fa0
Create Date: 2023-04-20 16:02:37.203402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8657b25530'
down_revision = 'c83c79c07fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('AdminId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('DateOfBirth', sa.DATETIME(), nullable=True),
    sa.Column('Account', sa.VARCHAR(length=128), nullable=True),
    sa.Column('Password', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('AdminId')
    )
    # ### end Alembic commands ###
