"""upgrade

Revision ID: 671818ebf392
Revises: 35970b48e68d
Create Date: 2023-04-13 15:27:06.459022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671818ebf392'
down_revision = '35970b48e68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chat',
    sa.Column('ChatId', sa.Integer(), nullable=False),
    sa.Column('ClientId1', sa.Integer(), nullable=True),
    sa.Column('ClientId2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ClientId1'], ['Client.ClientId'], ),
    sa.ForeignKeyConstraint(['ClientId2'], ['Client.ClientId'], ),
    sa.PrimaryKeyConstraint('ChatId')
    )
    with op.batch_alter_table('Message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ChatId', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Chat', ['ChatId'], ['ChatId'], ondelete='CASCADE')
        batch_op.drop_column('ReceiverId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ReceiverId', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Client', ['ReceiverId'], ['ClientId'])
        batch_op.drop_column('ChatId')

    op.drop_table('Chat')
    # ### end Alembic commands ###
