"""upgrade

Revision ID: c83c79c07fa0
Revises: 2d1d3c753cce
Create Date: 2023-04-20 14:00:05.196655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83c79c07fa0'
down_revision = '2d1d3c753cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ChatLastUpdate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Chat', schema=None) as batch_op:
        batch_op.drop_column('ChatLastUpdate')

    # ### end Alembic commands ###
